version: '3.4'

# sudo docker-compose up

services:
  redis:
    image: redis:latest
  api:
    image: reecepbcups/craft-rest-api:1.0.0
    # build: .
    depends_on:
      - redis
    ports:
      - '4000:4000'
    environment:
      - DAO_EXP_MODULE_ONLY=true
      - API_PORT=4000
      - REDIS_CONN_STRING=redis://redis:6379/0
      - CRAFTD_REST=http://65.108.125.182:1317
      - CRAFTD_NODE=http://65.108.125.182:26657
      - DAO_WALLETS=cosmos10r39fueph9fq7a6lgswu4zdsg8t3gxlqvvvyvn,osmo10r39fueph9fq7a6lgswu4zdsg8t3gxlqyhl56p,juno10r39fueph9fq7a6lgswu4zdsg8t3gxlq670lt0,dig10r39fueph9fq7a6lgswu4zdsg8t3gxlq5c90wg
      - CRAFT_ADMIN_WALLET=craft1hj5fveer5cjtn4wd6wstzugjfdxzl0xp86p9fl
      # If we also wanted to allow offerings via this too, we could for the API
      - ADDR721_REALESTATE="craft1wl59k23zngj34l7d42y9yltask7rjlnxgccawc7ltrknp6n52fpsaug5jn"
      - ADDR721_SKINS="craft1dt3lk455ed360pna38fkhqn0p8y44qndsr77qu73ghyaz2zv4whqgg28q2"
      - ADDRM="craft1fkwjqyfdyktgu5f59jpwhvl23zh8aav7f98ml9quly62jx2sehys8t86pv"